name: Build and Publish
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  semvar_gen:
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.3.0
      id: generate-version
      with:
        major_version: "(MAJOR)"
        minor_version: "(MINOR)"
        version_format: ${major}.${minor}.${patch}
        bump_each_version: true
