name: Build and Publish
on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  semvar_gen:
    runs-on: ubuntu-latest
    steps:
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.3.0
      id: generate-version
      with:
        major_pattern: "breaking:"
        minor_pattern: "feat:"
        version_format: ${major}.${minor}.${patch}
        search_commit_body: true
        bump_each_commit: true
